on: push
name: FTP Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest
      uses: actions/checkout@v2

    - name: Install Dependency
      run: npm install

    - name: Build
      run: npm run build

    - name: Save artifact
      uses: actions/upload-artifact@v1
      with:
        name: react-github-actions-build
        path: build

  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Get Artifact
      uses: actions/download-artifact@v2
      with:
        name: react-github-actions-build
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.server }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        protocol: ftp
        port: 21
